services:
    webapp:
        build:
            context: .
            dockerfile: Dockerfile
        working_dir: /var/www/html
        restart: always
        environment:
            DB_HOST: ${DB_HOST}
            DB_USER: ${DB_USERNAME}
            DB_PASSWORD: ${DB_PASSWORD}
            DB_NAME: ${DB_DATABASE}
        ports:
            - 8000:80
        volumes:
            - .:/var/www/html
        depends_on:
            - db
        networks:
            - app

    db:
        image: mysql:8.0.34
        environment:
            MYSQL_DATABASE: inventory
            MYSQL_ROOT_PASSWORD: password
        volumes:
            - mysql_data:/var/lib/mysql
        ports:
            - 3306:3306
        networks:
            - app

networks:
    app:
        driver: bridge

volumes:
    mysql_data: